spring:
  datasource:
    username: postgres
    password: 12345678
    url: "jdbc:postgresql://localhost:5432/adoptions"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update